/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CodeEntity {
  id: string
  name: string
  entityType: string
  filePath: string
  startLine: number
  endLine: number
  content: string
}
export interface SearchResult {
  file: string
  line: number
  content: string
  score: number
}
export interface ComplexityMetrics {
  cyclomatic: number
  cognitive: number
  linesOfCode: number
  maintainabilityIndex: number
}
export interface DuplicateResult {
  fileA: string
  fileB: string
  startLineA: number
  startLineB: number
  length: number
  content: string
}
/** Parse a file and extract entities using the real Tree-sitter parser. */
export declare function parseFile(filePath: string, content: string): Array<CodeEntity>
/** Index an entire codebase using the parallel Rust indexer. */
export declare function indexCodebase(path: string): string
/** Keyword search against the SQLite-backed code_entities table. */
export declare function searchCode(query: string, codebasePath?: string | undefined | null): Array<SearchResult>
/** Analyze cyclomatic / cognitive complexity for a code snippet. */
export declare function analyzeComplexity(content: string, filePath: string): ComplexityMetrics
/** Find duplicate code blocks across multiple files. */
export declare function findDuplicates(filePaths: Array<string>, contents: Array<string>, minLines: number): Array<DuplicateResult>
/**
 * Generate a deterministic mock embedding.
 * (Placeholder — Phase 5 will enable real ONNX embeddings.)
 */
export declare function generateEmbedding(text: string): Array<number>
/** Initialize the Rust engine (no-op for now — indexing engine is stateless). */
export declare function initEngine(): void
/** Get engine statistics (placeholder). */
export declare function getStatistics(): string
/** Clear indexed data (placeholder). */
export declare function clear(): void
