name: ✨ Feature Request
description: Suggest a new feature for CodeSight
title: '[FEATURE] '
labels: ['enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? If so, please describe it
      placeholder: I'm frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like CodeSight to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I have considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Core Functionality
        - MCP Protocol
        - User Interface
        - Performance
        - Documentation
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: As a user, I want to...

  - type: textarea
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      placeholder: This would be a game-changer for my workflow because...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to contribute to implementing this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/msenol/CodeSight/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided enough detail for the team to understand the request
          required: true
