pub mod indexing;
pub mod search;
pub mod embedding;
pub mod query_cache;
pub mod memory_profiler;
pub mod parallel_indexer;
pub mod storage;
pub mod analyzer;
pub mod security;
pub mod metrics;

pub use indexing::IndexingService;
pub use search::SearchService;
pub use embedding::EmbeddingService;
pub use query_cache::{QueryCache, QueryCacheConfig, QueryCacheStats};
pub use memory_profiler::{MemoryProfiler, MemoryProfilerConfig, MemoryReport, MemorySnapshot};
pub use parallel_indexer::{ParallelIndexer, ParallelIndexerConfig, IndexingTask, TaskPriority};
pub use storage::{StorageService, SQLiteStorage, StorageConfig, StorageType, DatabaseStats, QueryResult, Transaction, IsolationLevel};
pub use analyzer::{AnalyzerService, TreeSitterAnalyzer, AnalysisConfig, AnalysisResult, CodeEntity, EntityType, CodeRelationship, RelationshipType, FileMetrics, AnalysisIssue, Severity};
pub use security::{SecurityService, DefaultSecurityService, SecurityConfig, SecurityScan, SecurityFinding, FindingType, Severity as SecuritySeverity, Remediation, OWASPCategory};
pub use metrics::{MetricsService, DefaultMetricsService, MetricsConfig, MetricsReport, FileMetrics, DirectoryMetrics, MetricsSummary, Recommendation, TrendAnalysis, BenchmarkComparison, Grade};